[package]
name = "game_of_life_rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "game_of_life"
path = "src/game_of_life.rs"

[dependencies]
rand = "0.9.2"
raylib = { version = "5.5", features = [] }
